# Generated by Django 2.2.6 on 2020-04-05 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200401_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='images',
            new_name='image',
        ),
    ]
